Reduce memory usage and time consumption with large cpu cores.
lvis-dataset/lvis-api pull request #27
Opened 2021-07-12 05:07 UTC by shenyunhang

In my machine with 88 cpu core and 360G memory, ```lvis_challenge_2021``` branch takes hours to evaluate boundary ap with 10k results per category, and finally it runs out of memory.

I find the problme is from ```augment_annotations_with_boundary_multi_core``` function.
The ```multiprocessing``` module will create 88 workers, each of which copies parent process memory.
Thus, it causes high memory usage and time consumption in a machine with large number of cpu cores.

I modified the codes and only pass necessary arguments to ```augment_annotations_with_boundary_single_core``` function, instead of the ```LVIS``` class.
I also limited the max number of works to 80 in ```multiprocessing``` module.

The modifed codes only use about 100G memory with 80 wokers in ```augment_annotations_with_boundary_single_core``` function.
And the time consumption of generating boundary for 20M results is about 500s.

2021-07-13 17:13 UTC, agrimgupta92 requested changes
Thanks @shenyunhang for the pull request.

2021-07-13 17:13 UTC, agrimgupta92 commented on lvis/boundary_utils.py
> +    return mask_utils.decode(rle)
These functions are part of LVIS class. It would be good to avoid code repetition by removing these functions from lvis.py.

2021-07-13 17:13 UTC, agrimgupta92 commented on lvis/boundary_utils.py
> +MAX_CPU_NUM = 80
We should avoid hard coding the max_cpu_num limit. A better alternative can be to specify the number of workers as input argument while instantiating LVIS and LVISEval classes.

2021-07-15 02:59 UTC, shenyunhang commented
Thanks @agrimgupta92 for good suggestions.
I have modified the code to avoid code repetition and hard coding of the max_cpu_num limit.
The new code has been tested and works well.

2021-08-13 17:18 UTC, rbgirshick approved these changes
Thanks @shenyunhang for this PR! I've tested it on my system with the following results:
- Without this PR, I need to hack the max number of pool processes down to 20 to avoid a broken pipe error. Under this setting, evaluation took 1h03m.
- With this PR, I was able to run using 80 processes (the host has 80 cores) without any errors. Under this setting, evaluation took 26m.
- The AP values between the two runs were the same.

I've read the code and it looks good to me.

2021-08-16 15:05 UTC, merged